# Generated by Django 3.0.2 on 2020-01-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200123_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=30)),
        ),
    ]
