# Generated by Django 3.0.2 on 2020-01-29 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200123_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='link',
        ),
        migrations.RemoveField(
            model_name='song',
            name='slug',
        ),
    ]
