# Generated by Django 3.0.2 on 2020-01-30 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200130_1840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='search',
            new_name='result',
        ),
    ]
